remote_theme: "mmistakes/minimal-mistakes@4.13.0"

title: "NYU Tandon IDM | DM-GY 997X A | MS Thesis Fall 2018"





defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"


include: ["_pages"]